# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1032c54f1f94f8df737f04801a55b07e2be3e22ea1020de990bf4a5bf0f9a032e52f333274118926aca43a87ae485a9d9f937766b6561c70b2c4c619198440a

test:
  secret_key_base: e8601a8a1be328bab2fa13640fd15cd2fabf33264456b0b31d8462809d5675a046104c5dd63946019ab239e0a2b40ac220379bf503d7aaf0e1b28e554a85b57b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
